# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fmw-sa/Repos/OpenCV_for_suction_grasps

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fmw-sa/Repos/OpenCV_for_suction_grasps

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmw-sa/Repos/OpenCV_for_suction_grasps/CMakeFiles /home/fmw-sa/Repos/OpenCV_for_suction_grasps/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmw-sa/Repos/OpenCV_for_suction_grasps/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named contouring

# Build rule for target.
contouring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 contouring
.PHONY : contouring

# fast build rule for target.
contouring/fast:
	$(MAKE) -f CMakeFiles/contouring.dir/build.make CMakeFiles/contouring.dir/build
.PHONY : contouring/fast

#=============================================================================
# Target rules for targets named down_sampling

# Build rule for target.
down_sampling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 down_sampling
.PHONY : down_sampling

# fast build rule for target.
down_sampling/fast:
	$(MAKE) -f CMakeFiles/down_sampling.dir/build.make CMakeFiles/down_sampling.dir/build
.PHONY : down_sampling/fast

src/cpp/contouring.o: src/cpp/contouring.cpp.o
.PHONY : src/cpp/contouring.o

# target to build an object file
src/cpp/contouring.cpp.o:
	$(MAKE) -f CMakeFiles/contouring.dir/build.make CMakeFiles/contouring.dir/src/cpp/contouring.cpp.o
.PHONY : src/cpp/contouring.cpp.o

src/cpp/contouring.i: src/cpp/contouring.cpp.i
.PHONY : src/cpp/contouring.i

# target to preprocess a source file
src/cpp/contouring.cpp.i:
	$(MAKE) -f CMakeFiles/contouring.dir/build.make CMakeFiles/contouring.dir/src/cpp/contouring.cpp.i
.PHONY : src/cpp/contouring.cpp.i

src/cpp/contouring.s: src/cpp/contouring.cpp.s
.PHONY : src/cpp/contouring.s

# target to generate assembly for a file
src/cpp/contouring.cpp.s:
	$(MAKE) -f CMakeFiles/contouring.dir/build.make CMakeFiles/contouring.dir/src/cpp/contouring.cpp.s
.PHONY : src/cpp/contouring.cpp.s

src/cpp/down_sampling.o: src/cpp/down_sampling.cpp.o
.PHONY : src/cpp/down_sampling.o

# target to build an object file
src/cpp/down_sampling.cpp.o:
	$(MAKE) -f CMakeFiles/down_sampling.dir/build.make CMakeFiles/down_sampling.dir/src/cpp/down_sampling.cpp.o
.PHONY : src/cpp/down_sampling.cpp.o

src/cpp/down_sampling.i: src/cpp/down_sampling.cpp.i
.PHONY : src/cpp/down_sampling.i

# target to preprocess a source file
src/cpp/down_sampling.cpp.i:
	$(MAKE) -f CMakeFiles/down_sampling.dir/build.make CMakeFiles/down_sampling.dir/src/cpp/down_sampling.cpp.i
.PHONY : src/cpp/down_sampling.cpp.i

src/cpp/down_sampling.s: src/cpp/down_sampling.cpp.s
.PHONY : src/cpp/down_sampling.s

# target to generate assembly for a file
src/cpp/down_sampling.cpp.s:
	$(MAKE) -f CMakeFiles/down_sampling.dir/build.make CMakeFiles/down_sampling.dir/src/cpp/down_sampling.cpp.s
.PHONY : src/cpp/down_sampling.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... contouring"
	@echo "... down_sampling"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/cpp/contouring.o"
	@echo "... src/cpp/contouring.i"
	@echo "... src/cpp/contouring.s"
	@echo "... src/cpp/down_sampling.o"
	@echo "... src/cpp/down_sampling.i"
	@echo "... src/cpp/down_sampling.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

